apiVersion: v1
data:
  # each secret below needs to be encoded in base64.
  # e.g. to encode in base64 : "echo -n somebucketname | base64"
  endpoint: foofoofoofoo
  endpoint: foofoofoofoo
  accesskeyid: yyyyyyyyyyyy
  secretaccesskey: xxxxxxxxxxxxx
  inbucket:  aaaaaaaaa
  outbucket: bbbbbbbbb
kind: Secret
metadata:
  annotations:
  name: cos-secrets
type: Opaque
