---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: graph-bfs-trigger
spec:
  broker: default
  filter:
    attributes:
      type: graph-bfs
      source: curl
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: graph-bfs
