---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: dna-visualization-trigger
spec:
  broker: default
  filter:
    attributes:
      type: dna-visualization
      source: curl
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: dna-visualization
