---
kind: Service
apiVersion: serving.knative.dev/v1
metadata:
  name: graph-mst
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/ibm/knative-quarkus-bench/graph-mst:jvm
          name: benchmark
          env:
            - name: TYPE
              value: "printRetValTypeU"
