---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: dynamic-html-trigger
spec:
  broker: default
  filter:
    attributes:
      type: dynamicHtml
      source: curl
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: dynamic-html
