---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: network-trigger
spec:
  broker: default
  filter:
    attributes:
      type: network
      source: curl
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: network
