---
kind: Service
apiVersion: serving.knative.dev/v1
metadata:
  name: server-reply
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/ibm/knative-quarkus-bench/server-reply:jvm
          name: benchmark
          env:
            - name: TYPE
              value: "printRetValTypeD"
