---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: sleep-trigger
spec:
  broker: default
  filter:
    attributes:
      type: sleep
      source: curl
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sleep
