---
kind: Service
apiVersion: serving.knative.dev/v1
metadata:
  name: sleep
spec:
  template:
    metadata:
      labels:
        apps: benchmark
    spec:
      containers:
        - image: ghcr.io/ibm/knative-quarkus-bench/sleep:jvm
          name: benchmark
          env:
            - name: TYPE
              value: sleep
