---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: uploader-trigger
spec:
  broker: default
  filter:
    attributes:
      type: uploader
      source: curl
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: uploader
