---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: video-processing-trigger
spec:
  broker: default
  filter:
    attributes:
      type: video-processing
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: video-processing
