name: Native Workflow for Knative Quarkus Bench
on:
  push:
    paths-ignore:
      - '*.md'
      - '*.MD'
      - '.gitignore'
      - 'LICENSE'
      - '.github/workflows/github-action-jvm.yml'
jobs:
  build-native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "Event ${{ github.event_name }} triggered run on Github ${{ runner.os }} server."
      - run: echo "Branch ${{ github.ref }} and repo ${{ github.repository }}."
      - name: Check out repo code
        uses: actions/checkout@v3
      - run: echo "${{ github.repository }} repository cloned to runner."
      - name: Build and push Native images
        run:
          cd ${{ github.workspace }} && mvn clean package -Dquarkus.container-image.registry=ghcr.io -Dquarkus.container-image.group=ibm/knative-quarkus-bench -Dquarkus.container-image.push=true -Pnative
      - run: echo "Native build and push status ${{ job.status }}."
